// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PHMonitor.SQL;

#nullable disable

namespace PHMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PHMonitor.SQL.HardwareInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageCoreTemp")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageCoreVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("BusSpeed")
                        .HasColumnType("double precision");

                    b.Property<double>("CpuPackage")
                        .HasColumnType("double precision");

                    b.Property<double>("GpuCoreLoad")
                        .HasColumnType("double precision");

                    b.Property<double>("GpuCoreTemp")
                        .HasColumnType("double precision");

                    b.Property<string>("Motherboard")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalLoadPercentage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("HardwareInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
